### PR TITLE
Add test plan

### LINKED ISSUE #7: Test Plan
Fill out the test plan template.

### PR DESCRIPTION
**Pull request by dlarocque**
Test plan required for sprint 2.

Closes #7

### CODE REVIEW

**Review by BarbzCodez — APPROVED** [review]
lgtm :)

**Comment by BarbzCodez** [comment]
Might need to add the test plan link to readme

**Comment by dlarocque** [comment]
Some test cases need to be added before merge too; we don't have 10 per feature. Integration tests also need to be added.

**Review by VictoriaKGN — APPROVED** [review]
LGTM

**Pull request merged**
